name: Berkeley Ions
title: Berkeley Ions
description: >
  We are the Haeffner lab at UC Berkeley.
  We trap ions to investigate various aspects of quantum physics and quantum information.
theme: false
